-- H2 Sequences for testing
CREATE SEQUENCE IF NOT EXISTS "pr_seq_DEFAULT" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "po_seq_DEFAULT" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "grn_seq_DEFAULT" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "pr_seq_ACME" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "po_seq_ACME" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "grn_seq_ACME" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "pr_seq_TECH" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "po_seq_TECH" START WITH 1;
CREATE SEQUENCE IF NOT EXISTS "grn_seq_TECH" START WITH 1;
