-- V28: Removed — department-specific custody mapping seed data was based on phantom Keycloak
-- groups (it-team, finance-leads, etc.) that do not exist in the realm. Custody mappings
-- must be created by admins via the portal once real candidate groups are configured.
-- See V29 for cleanup of any previously applied rows.
